#!/usr/bin/env python3
"""Prepare an isolated MiMo Codex home without changing running CCDM sessions."""

import argparse
import getpass
import json
import os
from pathlib import Path
import re
import sys
import tempfile
import urllib.request


CATALOG_URL = "https://example-files.cnbj1.mi-fds.com/example-files/configs/model-catalogs.json"
ENDPOINTS = {
    "payg": "https://api.xiaomimimo.com/v1",
    "token-plan": "https://token-plan-cn.xiaomimimo.com/v1",
}


def read_key(billing):
    # No command-line key option: avoid shell history and process arguments.
    key = os.environ.get("MIMO_API_KEY")
    if key is None:
        key = getpass.getpass("MiMo API key: ") if sys.stdin.isatty() else sys.stdin.read()
    key = key.strip()
    pattern = r"sk-[A-Za-z0-9_-]+" if billing == "payg" else r"(?:tp|ttp)-[A-Za-z0-9_-]+"
    if not re.fullmatch(pattern, key):
        raise ValueError("API key is missing or does not match the selected billing method")
    return key


def read_catalog(file, model):
    if file:
        data = Path(file).read_bytes()
    else:
        with urllib.request.urlopen(CATALOG_URL, timeout=30) as response:
            data = response.read(4 * 1024 * 1024 + 1)
    if len(data) > 4 * 1024 * 1024:
        raise ValueError("Model catalog exceeds 4 MiB")
    catalog = json.loads(data)
    models = catalog.get("models") if isinstance(catalog, dict) else None
    if not isinstance(models, list) or not all(isinstance(item, dict) for item in models):
        raise ValueError("Model catalog must contain a models array")
    selected = next((item for item in models if item.get("slug") == model), None)
    if selected is None or selected.get("use_responses_lite") is not True:
        raise ValueError("Selected model is missing or does not enable Responses lite tool support")
    if selected.get("supports_reasoning_summaries") is not True:
        raise ValueError("Selected model must declare reasoning support in the catalog")
    return catalog


def configuration(home, billing, model):
    # JSON strings are valid TOML basic strings for these paths and identifiers.
    # Keep Unicode literal: JSON surrogate-pair escapes are not valid TOML.
    def quote(value):
        return json.dumps(value, ensure_ascii=False)
    return f'''# Generated by CCDM setup-codex-mimo.py. Credentials stay in api-key.
model = {quote(model)}
model_provider = "mimo"
model_reasoning_effort = "high"
model_reasoning_summary = "none"
model_context_window = 1048576
web_search = "disabled"
model_catalog_json = {quote(str(home / "model-catalogs.json"))}

[model_providers.mimo]
name = "MiMo"
base_url = {quote(ENDPOINTS[billing])}
wire_api = "responses"

[model_providers.mimo.auth]
command = "/bin/cat"
args = [{quote(str(home / "api-key"))}]
'''


def write_private(path, content):
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as output:
        output.write(content)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--home", default="~/.codex-mimo", help="New, external Codex home (must not exist)")
    parser.add_argument("--billing", choices=ENDPOINTS, default="payg")
    parser.add_argument("--model", default="mimo-v2.6-pro")
    parser.add_argument("--catalog-file", help="Use a local vendor catalog instead of downloading it")
    parser.add_argument("--rotate-key", action="store_true", help="Replace only the key in an existing generated home")
    args = parser.parse_args()
    home = Path(os.path.abspath(os.path.expanduser(args.home)))
    repo = Path(__file__).resolve().parent.parent
    if home.resolve() == repo or repo in home.resolve().parents:
        raise ValueError("Codex homes must live outside the CCDM checkout")
    if home.is_symlink():
        raise ValueError("Codex home must not be a symlink")
    if args.rotate_key:
        # Refuse arbitrary homes, symlinks, and accidental billing changes.
        config = home / "config.toml"
        marker = home / "ccdm-mimo.json"
        key_path = home / "api-key"
        if not home.is_dir() or config.is_symlink() or marker.is_symlink() or key_path.is_symlink():
            raise ValueError("Key rotation requires an existing generated MiMo home")
        metadata = json.loads(marker.read_text())
        if (metadata != {"version": 1, "billing": args.billing}
                or not config.is_file() or not key_path.is_file()):
            raise ValueError("Home configuration differs; use its original billing settings or rotate manually")
        key = read_key(args.billing)
        fd, temporary = tempfile.mkstemp(prefix=".api-key-", dir=home)
        try:
            with os.fdopen(fd, "w") as output:
                output.write(key + "\n")
            os.replace(temporary, key_path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
        print("MiMo key replaced. Restart only sessions using this home to refresh authentication.")
        return
    if home.exists():
        raise ValueError("Codex home already exists; choose a new path or use --rotate-key")
    key = read_key(args.billing)
    catalog = read_catalog(args.catalog_file, args.model)
    # Validate everything before creating the home; never overwrite existing state.
    home.mkdir(mode=0o700, parents=True)
    write_private(home / "api-key", key + "\n")
    write_private(home / "model-catalogs.json", json.dumps(catalog, indent=2) + "\n")
    write_private(home / "config.toml", configuration(home, args.billing, args.model))
    write_private(home / "ccdm-mimo.json", json.dumps({"version": 1, "billing": args.billing}) + "\n")
    print(f"Created MiMo Codex home: {home}")
    print("Add its path to codex_accounts and select the alias on a Codex project.")
    print("No registry entries, defaults, or running sessions were changed.")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError) as error:
        # Do not print request bodies, credentials, or configuration contents.
        print(f"MiMo setup failed: {error}", file=sys.stderr)
        sys.exit(1)
