#!/usr/bin/env python3
"""Prepare an isolated DeepSeek Codex home without changing running CCDM sessions."""

import argparse
import getpass
import json
import os
from pathlib import Path
import re
import sys
import tempfile
import urllib.request


CATALOG_URL = "https://cdn.deepseek.com/api-docs/codex-deepseek-setup-en.sh"
MODEL = "deepseek-flash"
BASE_URL = "https://api.deepseek.com/"


def read_key():
    # No command-line key option: avoid shell history and process arguments.
    key = os.environ.get("DEEPSEEK_API_KEY")
    if key is None:
        key = getpass.getpass("DeepSeek API key: ") if sys.stdin.isatty() else sys.stdin.read()
    if not isinstance(key, str) or not re.fullmatch(r"sk-[A-Za-z0-9_-]+", key.strip()):
        raise ValueError("A valid DeepSeek API key is required")
    return key.strip()


def read_catalog(file):
    if file:
        with open(file, "rb") as source:
            data = source.read(4 * 1024 * 1024 + 1)
    else:
        with urllib.request.urlopen(CATALOG_URL, timeout=30) as response:
            data = response.read(4 * 1024 * 1024 + 1)
    if len(data) > 4 * 1024 * 1024:
        raise ValueError("Model catalog source exceeds 4 MiB")
    text = data.decode("utf-8")
    if not text.lstrip().startswith("{"):
        # Extract the vendor's literal JSON heredoc as data. NEVER run its shell script.
        blocks = re.findall(r"<<'CODEX_MODELS_JSON'\r?\n(.*?)\r?\nCODEX_MODELS_JSON(?:\r?\n|$)", text, re.S)
        if len(blocks) != 1:
            raise ValueError("Vendor catalog layout changed; supply a JSON --catalog-file")
        text = blocks[0]
    catalog = json.loads(text)
    models = catalog.get("models") if isinstance(catalog, dict) else None
    if not isinstance(models, list) or not all(isinstance(item, dict) for item in models):
        raise ValueError("Model catalog must contain a models array")
    selected = [item for item in models if item.get("slug") == MODEL]
    if len(selected) != 1:
        raise ValueError("Model catalog must contain exactly one deepseek-flash entry")
    model = selected[0]
    if (model.get("use_responses_lite") is not False
            or model.get("tool_mode") is not None
            or model.get("shell_type") != "shell_command"
            or model.get("apply_patch_tool_type") != "freeform"):
        raise ValueError("DeepSeek catalog must use standard Responses and compatible shell/patch tools")
    modalities = model.get("input_modalities")
    reasoning = model.get("supported_reasoning_levels")
    if (not isinstance(modalities, list) or "text" not in modalities or "image" not in modalities
            or model.get("supports_reasoning_summaries") is not True
            or not isinstance(reasoning, list)
            or not any(isinstance(level, dict) and level.get("effort") == "high"
                       for level in reasoning)):
        raise ValueError("DeepSeek Flash catalog must declare vision and high reasoning support")
    return {"models": selected}


def configuration(home):
    # JSON strings are valid TOML basic strings for these paths and identifiers.
    # Keep Unicode literal: JSON surrogate-pair escapes are not valid TOML.
    def quote(value):
        return json.dumps(value, ensure_ascii=False)
    return f'''# Generated by CCDM setup-codex-deepseek.py. Credentials stay in api-key.
model = {quote(MODEL)}
model_provider = "deepseek"
model_reasoning_effort = "high"
model_reasoning_summary = "none"
model_context_window = 1048576
web_search = "disabled"
model_catalog_json = {quote(str(home / "model-catalogs.json"))}

[model_providers.deepseek]
name = "DeepSeek"
base_url = {quote(BASE_URL)}
wire_api = "responses"

[model_providers.deepseek.auth]
command = "/bin/cat"
args = [{quote(str(home / "api-key"))}]
'''


def write_private(path, content):
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as output:
        output.write(content)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--home", default="~/.codex-deepseek", help="New, external Codex home (must not exist)")
    parser.add_argument("--catalog-file", help="Use a local catalog JSON or vendor setup script as data")
    parser.add_argument("--rotate-key", action="store_true", help="Replace only the key in an existing generated home")
    args = parser.parse_args()
    home = Path(os.path.abspath(os.path.expanduser(args.home)))
    repo = Path(__file__).resolve().parent.parent
    if home.resolve() == repo or repo in home.resolve().parents:
        raise ValueError("Codex homes must live outside the CCDM checkout")
    if home.is_symlink():
        raise ValueError("Codex home must not be a symlink")
    if args.rotate_key:
        # Refuse arbitrary homes and symlinks; preserve unrelated configuration.
        config = home / "config.toml"
        marker = home / "ccdm-deepseek.json"
        key_path = home / "api-key"
        if not home.is_dir() or config.is_symlink() or marker.is_symlink() or key_path.is_symlink():
            raise ValueError("Key rotation requires an existing generated DeepSeek home")
        metadata = json.loads(marker.read_text())
        if (metadata != {"version": 1, "provider": "deepseek"}
                or not config.is_file() or not key_path.is_file()):
            raise ValueError("Key rotation requires a home generated by the DeepSeek setup helper")
        key = read_key()
        fd, temporary = tempfile.mkstemp(prefix=".api-key-", dir=home)
        try:
            with os.fdopen(fd, "w") as output:
                output.write(key + "\n")
            os.replace(temporary, key_path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
        print("DeepSeek key replaced. Restart only sessions using this home to refresh authentication.")
        return
    if home.exists():
        raise ValueError("Codex home already exists; choose a new path or use --rotate-key")
    key = read_key()
    catalog = read_catalog(args.catalog_file)
    # Validate everything before creating the home; never overwrite existing state.
    home.mkdir(mode=0o700, parents=True)
    write_private(home / "api-key", key + "\n")
    write_private(home / "model-catalogs.json", json.dumps(catalog, indent=2) + "\n")
    write_private(home / "config.toml", configuration(home))
    write_private(home / "ccdm-deepseek.json", json.dumps({"version": 1, "provider": "deepseek"}) + "\n")
    print(f"Created DeepSeek Codex home: {home}")
    print("Add its path to codex_accounts and select the alias on a Codex project.")
    print("No registry entries, defaults, or running sessions were changed.")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError) as error:
        # Do not print request bodies, credentials, or configuration contents.
        print(f"DeepSeek setup failed: {error}", file=sys.stderr)
        sys.exit(1)
